### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**

### CODE REVIEW

**Comment by GodGun968** [comment]
not yet completed Don‘t merge

**Comment by GodGun968** [comment]
😢Why failed, Is it related to me?

**Comment by deirn** [comment]
Seems to be some Maven repository issue. Your changes look fine.

**Comment by GodGun968** [comment]
okay...

**Comment by GodGun968** [comment]
Which mods does the feature in Waila Extra work with?

**Comment by deirn** [comment]
You should merge 09d768c2f1cc26813a60c6417050dabc080fd2f1, that should fix the build failing.

---

> Which mods does the feature in Waila Extra work with?

Mods that use Fabric API/Forge Capability to handle it's inventory should work out of the box. I have https://github.com/badasintended/megane update prepared to use the new API locally, though I'm still need to test that and I'm pretty busy right now.

**Comment by GodGun968** [comment]
already merge

**Review by deirn — APPROVED** [review]

**Pull request merged**
