### PR TITLE
[RU-RU] Added and translated missing lines

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by deirn** [comment]
Can you target the master branch instead? Also please don't change the formatting, it makes it confusing to know what actually changed.

**Comment by ghost** [comment]
As for formatting, I just edited the original ru_ru.json from the jar... I just downloaded Notepad++, should I re-edit the file inside the repository or is there some feature in Notepad++ to do it quickly?

**Comment by deirn** [comment]
I don't know about Notepad++, but you can use https://github.dev/badasintended/wthit to edit files in the browser.

**Comment by ghost** [comment]
> I don't know about Notepad++, but you can use https://github.dev/badasintended/wthit to edit files in the browser.

I created a new pull request to the main branch and tried to return your formatting, but in my editor it looks a little different than when I view it not on GH editor...

**Pull request closed without merging**
