### PR TITLE
fix number formatting

### PR DESCRIPTION
**Pull request by dou867**

### CODE REVIEW

**Comment by deirn** [comment]
I'm not sure, what issue this PR fix?

**Comment by dou867** [comment]
This mod crashes my game when used with bigger stack mods.

**Comment by dou867** [comment]
and `number / Math.pow(1000, exp)` just doesn't look correct.

**Comment by deirn** [comment]
> This mod crashes my game when used with bigger stack mods.

Can i see the crash log?

**Comment by dou867** [comment]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:1512)
	at mcp.mobius.waila.util.DisplayUtil.shortHandNumber(DisplayUtil.java:47)
	at mcp.mobius.waila.util.DisplayUtil.renderStack(DisplayUtil.java:26)
	at mcp.mobius.waila.plugin.vanilla.renderer.ItemRenderer.draw(ItemRenderer.java:27)
	at mcp.mobius.waila.hud.component.DrawableComponent$RendererContainer.render(DrawableComponent.java:152)
	at mcp.mobius.waila.hud.component.DrawableComponent.render(DrawableComponent.java:66)
	at mcp.mobius.waila.hud.TooltipRenderer.render(TooltipRenderer.java:213)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)

**Comment by dou867** [comment]
image
This is what it should display after the fix.

**Comment by deirn** [comment]
Changing `log(number / 1000.0)` to `log(number) / log(1000)` would suffice

**Pull request merged**
