### PR TITLE
Make default set of blacklist configurable?

### PR DESCRIPTION
**Pull request by ghost**
Hello. I have a thought <s>(an issue)</s> regarding the vanilla blacklist setting. The plugin `WailaPluginVanilla` invokes `addBlacklist` method, so it adds several blocks and entity types to `blacklist.json` by default. In my circumstance I want the barrier block tooltip shown (https://github.com/badasintended/wthit/pull/75), I don't like editing the json file every time I launch game, especially when playing on a server that doesn't even implement any modding API like fabric or forge at all, in which case the datapack approach won't actually help either. Because of the plugin, every time barrier block will be added back to the blacklist. Say removing barrier block from blacklist **once for all** is my personal configuration, but the plugin doesn't seem to be respecting the setting.

I make a simple <s>(or simp)</s> change. Similar to `WailaPluginExtra`, `WailaPluginVanilla` has another config class `DefaultRollbackBlacklistConfig` which will be only involved in the `WailaPluginVanilla`'s registration, during which `default_blacklist.json` will be created or looked up. If the json doesn't exist, some default values will be written, and then invoke `addBlacklist` method in `WailaPluginVanilla` using all the values from `default_blacklist.json`.

And of course having manually modified `default_blacklist.json` into effect requires restarting game, while `blacklist.json` is a live config (the `invalidate` method).

I rolled out several manual tests on Minecraft Fabric 1.20.1, and it worked as expected. One notable thing though, when I purposefully edited `default_blacklist.json` into a wrong format, exception was thrown (the `ConfigIo` class does the magic), the json file was reset and all the three arrays went empty, right before invoking `addBlacklist`, I think it's due to the `DefaultRollbackBlacklistConfig`'s constructor (the `Supplier` factory does the work).

Not 100% sure what I am missing (I see the translation key is missing). I believe offering a convenient approach to making customized default set of blacklist could be better. Any suggestion?

i1

### CODE REVIEW

**Comment by deirn** [comment]
> Because of the plugin, every time barrier block will be added back to the blacklist. Say removing barrier block from blacklist once for all is my personal configuration, but the plugin doesn't seem to be respecting the setting.

The `addBlacklist` should respect the config value _if_ the plugin doesn't add/remove entry and changes the hash value:

- Hash the blacklist entries from plugins.
- Compare the hash with the `pluginHash` value from the config.
- Backup the config and reset if the hash mismatched, use the config value otherwise.

Does it reset the config even if the plugin doesn't change? If so, then that's the one that should be fixed instead of this PR.

**Comment by ghost** [comment]
Just tried the latest release again and unfortunately the barrier block gets re-added to blacklist every time I launch game.

The `addBlacklist` itself should be fine. I think the issue probably lies in the `lock` method in `Registrar` enum class.

The `addBlacklist` adds values to the `blacklist` field declared in `Registrar`. Right in `lock`, after checking the json's existence, comparing the hash value, all the blacklist values in `blacklist` are added to the actual functioning `BLACKLIST_CONFIG`, then written to the json:

```java
if (Waila.BLACKLIST_CONFIG.isFileExists() && !Arrays.equals(Waila.BLACKLIST_CONFIG.get().pluginHash, hash)) {
    Waila.BLACKLIST_CONFIG.backup();
}

BlacklistConfig newBlacklist = Waila.BLACKLIST_CONFIG.get();
newBlacklist.pluginHash = hash;
newBlacklist.blocks.addAll(blacklist.blocks);
newBlacklist.entityTypes.addAll(blacklist.entityTypes);
Waila.BLACKLIST_CONFIG.save();
```

This is probably why the barrier block gets re-added again and again, same as other default blacklist values in `WailaPluginVanilla`'s registration.

Honestly, from an average player's perspective, I don't ever focus on the `configVersion` and `pluginHash` section (Long ago I didn't know what are these for), after upgrading from Hwyla to WTHIT on Minecraft Fabric 1.19.3, before investigating into these src, I was quite frustrated why the config gets reverted all the time.

**Comment by ghost** [comment]
At first I deleted `blacklist.json` on purpose to have it re-generated. I get the following:
```json
"configVersion": 0,
"pluginHash": [
  1510828157,
  0,
  -846312502
]
```
I rolled out some manual tests. I remove `"minecraft:barrier"` from blacklist then relaunch game, it gets reverted. The plugin hash doesn't change all the time. Any value other than all these default values get perfectly saved.

**Comment by ghost** [comment]
I think I may have found a proper fix. I am closing this PR sooner or later and (maybe) open a new one.

**Pull request closed without merging**
